[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=+simd128,+bulk-memory,+mutable-globals",
    "-C", "llvm-args=-cost-kind=throughput",
]

[build]
target = "wasm32-unknown-unknown"
